use core::arch::asm;
use core::sync::atomic::{AtomicU64, Ordering};

/// Minimal generic-timer bring-up target:
/// - read CNTFRQ_EL0
/// - program CNTP_TVAL_EL0
/// - enable CNTP_CTL_EL0
///
/// We deliberately stop here for this phase. Delivering the interrupt to EL1
/// still requires the GIC/IRQ path, which comes next.
const CNTP_CTL_ENABLE: u32 = 1 << 0;
const CNTP_CTL_ISTATUS: u32 = 1 << 2;

/// Early bring-up default: 1 ms periodic tick.
pub const EARLY_TICK_HZ: u64 = 1000;
pub const TIMER_IRQ_ID_PHYS: u32 = 30;

#[unsafe(no_mangle)]
pub static mut BOOT_TIMER_FREQ_HZ: u64 = 0;
#[unsafe(no_mangle)]
pub static mut BOOT_TIMER_RELOAD_TICKS: u64 = 0;
#[unsafe(no_mangle)]
pub static mut BOOT_TIMER_CTL: u64 = 0;
#[unsafe(no_mangle)]
pub static mut BOOT_TIMER_COUNTER: u64 = 0;
#[unsafe(no_mangle)]
pub static BOOT_TIMER_IRQ_COUNT: AtomicU64 = AtomicU64::new(0);

#[inline(always)]
pub fn frequency_hz() -> u64 {
    let value: u64;
    unsafe {
        asm!(
            "mrs {value}, CNTFRQ_EL0",
            value = out(reg) value,
            options(nomem, nostack, preserves_flags)
        );
    }
    value
}

#[inline(always)]
pub fn counter() -> u64 {
    let value: u64;
    unsafe {
        asm!(
            "mrs {value}, CNTPCT_EL0",
            value = out(reg) value,
            options(nomem, nostack, preserves_flags)
        );
    }
    value
}

#[inline(always)]
pub fn control() -> u32 {
    let value: u64;
    unsafe {
        asm!(
            "mrs {value}, CNTP_CTL_EL0",
            value = out(reg) value,
            options(nomem, nostack, preserves_flags)
        );
    }
    value as u32
}

#[inline(always)]
pub unsafe fn write_tval(ticks: u32) {
    unsafe {
        asm!(
            "msr CNTP_TVAL_EL0, {value}",
            value = in(reg) ticks as u64,
            options(nomem, nostack, preserves_flags)
        );
        asm!("isb", options(nomem, nostack, preserves_flags));
    }
}

#[inline(always)]
pub unsafe fn write_ctl(value: u32) {
    unsafe {
        asm!(
            "msr CNTP_CTL_EL0, {value}",
            value = in(reg) value as u64,
            options(nomem, nostack, preserves_flags)
        );
        asm!("isb", options(nomem, nostack, preserves_flags));
    }
}

#[inline(always)]
pub fn ticks_from_hz(freq_hz: u64, tick_hz: u64) -> u32 {
    let tick_hz = tick_hz.max(1);
    let ticks = (freq_hz / tick_hz).max(1);
    ticks.min(u32::MAX as u64) as u32
}

#[inline(always)]
pub unsafe fn arm_in_ticks(ticks: u32) {
    unsafe {
        write_tval(ticks);
        // ENABLE=1, IMASK=0: timer interrupt is generated by the architected timer.
        // Actual delivery to EL1 will happen once the GIC/IRQ path is brought up.
        write_ctl(CNTP_CTL_ENABLE);
    }
}

#[inline(always)]
pub unsafe fn disable() {
    unsafe {
        write_ctl(0);
    }
}

/// Early timer programming used before the full interrupt stack exists.
///
/// This is intentionally simple and observable from GDB:
/// - BOOT_TIMER_FREQ_HZ
/// - BOOT_TIMER_RELOAD_TICKS
/// - BOOT_TIMER_CTL
/// - BOOT_TIMER_COUNTER
pub unsafe fn early_init() {
    let freq = frequency_hz();
    let reload = ticks_from_hz(freq, EARLY_TICK_HZ);

    unsafe {
        BOOT_TIMER_FREQ_HZ = freq;
        BOOT_TIMER_RELOAD_TICKS = reload as u64;
        BOOT_TIMER_COUNTER = counter();

        arm_in_ticks(reload);

        let ctl = control();
        BOOT_TIMER_CTL = ctl as u64;
    }

    let _ = CNTP_CTL_ISTATUS;
}

#[inline(always)]
pub unsafe fn enable_cpu_irq() {
    unsafe {
        // Clear IRQ mask bit in DAIF.
        asm!("msr daifclr, #2", options(nomem, nostack, preserves_flags));
        asm!("isb", options(nomem, nostack, preserves_flags));
    }
}

#[inline(always)]
pub fn irq_count() -> u64 {
    BOOT_TIMER_IRQ_COUNT.load(Ordering::Relaxed)
}

pub fn on_timer_irq() {
    BOOT_TIMER_IRQ_COUNT.fetch_add(1, Ordering::Relaxed);

    // For first bring-up keep it one-shot to avoid IRQ storm.
    unsafe {
        disable();
    }
}
